sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rzinovyev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rzinovyev/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-759428561002"
  bucket_path: "docker-react"
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: 
  secure: "$AWS_SECRET_KEY"    